# Generated by Django 2.2 on 2019-04-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Album', max_length=50, verbose_name='Name')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('about', models.TextField(blank=True, help_text='About Album', null=True, verbose_name='Description')),
                ('thumbnail', models.ImageField(default='static/album/default.jpg', help_text='Upload Image of the Artist', upload_to='static/album/images', verbose_name='Image')),
                ('is_fav', models.BooleanField(default=False, help_text='Tick if favourite', verbose_name='Favourite')),
                ('release_date', models.DateField(blank=True, help_text='Release date of Album', null=True, verbose_name='Release Year')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the Artist', max_length=50, verbose_name='Name')),
                ('about', models.TextField(blank=True, help_text='About Artist', null=True, verbose_name='About')),
                ('thumbnail', models.ImageField(default='static/artist/default.jpg', help_text='Uplaod Image of the Artist', upload_to='static/artist/images', verbose_name='Image')),
                ('birth_date', models.DateField(blank=True, help_text='Birth date of Artist', null=True, verbose_name='Birth Date')),
                ('is_fav', models.BooleanField(default=False, help_text='Tick if favourite', verbose_name='Favourite')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Track', max_length=50, verbose_name='Name')),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True, verbose_name='About')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Track', max_length=50, verbose_name='Name')),
                ('duration', models.DurationField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, help_text='Track lyrics', null=True, verbose_name='Lyrics')),
                ('is_fav', models.BooleanField(default=False, help_text='Tick if favourite', verbose_name='Favourite')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='music_catalog.Album')),
                ('artist', models.ManyToManyField(related_name='track_artist', to='music_catalog.Artist')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='music_catalog.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='music_catalog.Genre'),
        ),
    ]
