# Generated by Django 2.2 on 2019-04-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_catalog', '0002_remove_artist_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='thumbnail',
            field=models.ImageField(default='static/artist/default.jpg', help_text='Uplaod Image of the Artist', upload_to='static/artist/images', verbose_name='Image'),
        ),
    ]
