# Generated by Django 2.1.7 on 2019-03-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_overview', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
