# Generated by Django 2.1.7 on 2019-03-19 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='users',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
