# Generated by Django 2.2 on 2019-05-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='albumgenre',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='albumgenre',
            name='album',
        ),
        migrations.RemoveField(
            model_name='albumgenre',
            name='genre',
        ),
        migrations.AlterUniqueTogether(
            name='trackartist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trackartist',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='trackartist',
            name='track',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='music_catalog_app.Artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='music_catalog_app.Genre'),
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(to='music_catalog_app.Artist'),
        ),
        migrations.DeleteModel(
            name='AlbumArtist',
        ),
        migrations.DeleteModel(
            name='AlbumGenre',
        ),
        migrations.DeleteModel(
            name='TrackArtist',
        ),
    ]
