# Generated by Django 2.1.7 on 2019-03-18 23:19

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField(default=todo_app.models.days_from_now_1, verbose_name='due')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
