# Generated by Django 2.2 on 2019-04-17 23:20

from django.db import migrations, models
import todo_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Task Description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due',
            field=models.DateTimeField(default=todo_app.models.days_from_now_1, help_text='Task Due (default - 1 day from now)', verbose_name='due'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Task Title', max_length=100, verbose_name='Title'),
        ),
    ]
