# Generated by Django 2.2 on 2019-04-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(help_text='Task image', upload_to='media/images', verbose_name='Image'),
        ),
    ]
