# Generated by Django 2.2 on 2019-04-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_auto_20190424_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, help_text='Task image', upload_to='images/', verbose_name='Image'),
        ),
    ]
